In [2]:
#1
import yfinance as yf
import pandas as pd

# Extracting Tesla Stock Data
tesla = yf.Ticker("TSLA")
tesla_data = tesla.history(period="max")
tesla_data.reset_index(inplace=True)

# Displaying the first few rows of the dataframe
tesla_data.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2010-06-29 00:00:00-04:00,1.266667,1.666667,1.169333,1.592667,281494500,0.0,0.0
1,2010-06-30 00:00:00-04:00,1.719333,2.028000,1.553333,1.588667,257806500,0.0,0.0
2,2010-07-01 00:00:00-04:00,1.666667,1.728000,1.351333,1.464000,123282000,0.0,0.0
3,2010-07-02 00:00:00-04:00,1.533333,1.540000,1.247333,1.280000,77097000,0.0,0.0
4,2010-07-06 00:00:00-04:00,1.333333,1.333333,1.055333,1.074000,103003500,0.0,0.0

In [4]:
#2
import yfinance as yf
import pandas as pd
from alpha_vantage.fundamentaldata import FundamentalData
import plotly.graph_objects as go


# Extracting Tesla Revenue Data
api_key = 'YOUR_API_KEY'  # Replace with your actual API key from Alpha Vantage
fd = FundamentalData(key=api_key, output_format='pandas')
revenue_data, meta_data = fd.get_income_statement_annual(symbol='TSLA')

# Displaying the first few rows of the Tesla revenue data
print(revenue_data.head())

                              fiscalDateEnding reportedCurrency  grossProfit  \
date
1970-01-01 00:00:00.000000000       2023-12-31              USD  17660000000
1970-01-01 00:00:00.000000001       2022-12-31              USD  20853000000
1970-01-01 00:00:00.000000002       2021-12-31              USD  13606000000
1970-01-01 00:00:00.000000003       2020-12-31              USD   6630000000
1970-01-01 00:00:00.000000004       2019-12-31              USD   4069000000

                              totalRevenue costOfRevenue  \
date
1970-01-01 00:00:00.000000000  96773000000   79113000000
1970-01-01 00:00:00.000000001  81462000000   60609000000
1970-01-01 00:00:00.000000002  53823000000   40217000000
1970-01-01 00:00:00.000000003  31536000000   24906000000
1970-01-01 00:00:00.000000004  24578000000   20509000000

                              costofGoodsAndServicesSold operatingIncome  \
date
1970-01-01 00:00:00.000000000                  463000000      8891000000
1970-01-01 00:00:00.000000001                  604000000     13656000000
1970-01-01 00:00:00.000000002                  374000000      6523000000
1970-01-01 00:00:00.000000003                  289000000      1994000000
1970-01-01 00:00:00.000000004                  193000000       -69000000

                              sellingGeneralAndAdministrative  \
date
1970-01-01 00:00:00.000000000                      4800000000
1970-01-01 00:00:00.000000001                      3946000000
1970-01-01 00:00:00.000000002                      4517000000
1970-01-01 00:00:00.000000003                      3145000000
1970-01-01 00:00:00.000000004                      2646000000

                              researchAndDevelopment operatingExpenses  ...  \
date                                                                    ...
1970-01-01 00:00:00.000000000             3969000000        8769000000  ...
1970-01-01 00:00:00.000000001             3075000000        7197000000  ...
1970-01-01 00:00:00.000000002             2593000000        7083000000  ...
1970-01-01 00:00:00.000000003             1491000000        4636000000  ...
1970-01-01 00:00:00.000000004             1343000000        4138000000  ...

                              depreciation depreciationAndAmortization  \
date
1970-01-01 00:00:00.000000000   3330000000                   506000000
1970-01-01 00:00:00.000000001   2420000000                   493000000
1970-01-01 00:00:00.000000002   1910000000                   466000000
1970-01-01 00:00:00.000000003   1570000000                   399000000
1970-01-01 00:00:00.000000004   1370000000                   343000000

                              incomeBeforeTax incomeTaxExpense  \
date
1970-01-01 00:00:00.000000000      9996000000      -5001000000
1970-01-01 00:00:00.000000001     13688000000       1130000000
1970-01-01 00:00:00.000000002      6218000000        699000000
1970-01-01 00:00:00.000000003      1013000000        292000000
1970-01-01 00:00:00.000000004      -752000000        110000000

                              interestAndDebtExpense  \
date
1970-01-01 00:00:00.000000000              156000000
1970-01-01 00:00:00.000000001              191000000
1970-01-01 00:00:00.000000002              371000000
1970-01-01 00:00:00.000000003              853000000
1970-01-01 00:00:00.000000004              685000000

                              netIncomeFromContinuingOperations  \
date
1970-01-01 00:00:00.000000000                       14974000000
1970-01-01 00:00:00.000000001                       12587000000
1970-01-01 00:00:00.000000002                        5644000000
1970-01-01 00:00:00.000000003                         862000000
1970-01-01 00:00:00.000000004                        -775000000

                              comprehensiveIncomeNetOfTax         ebit  \
date
1970-01-01 00:00:00.000000000                 15215000000  10152000000
1970-01-01 00:00:00.000000001                 12141000000  13879000000
1970-01-01 00:00:00.000000002                  5210000000   6589000000
1970-01-01 00:00:00.000000003                  1120000000   1761000000
1970-01-01 00:00:00.000000004                  -890000000    -67000000

                                    ebitda    netIncome
date
1970-01-01 00:00:00.000000000  10658000000  14997000000
1970-01-01 00:00:00.000000001  14372000000  12556000000
1970-01-01 00:00:00.000000002   7055000000   5519000000
1970-01-01 00:00:00.000000003   2160000000    721000000
1970-01-01 00:00:00.000000004    276000000   -862000000

[5 rows x 26 columns]

In [5]:
#3
import yfinance as yf
import pandas as pd

# Extracting GameStop Stock Data
gamestop = yf.Ticker("GME")
gamestop_data = gamestop.history(period="max")
gamestop_data.reset_index(inplace=True)

# Displaying the first few rows of the GameStop stock data
gamestop_data.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2002-02-13 00:00:00-05:00,1.620129,1.693350,1.603296,1.691667,76216000,0.0,0.0
1,2002-02-14 00:00:00-05:00,1.712707,1.716074,1.670626,1.683250,11021600,0.0,0.0
2,2002-02-15 00:00:00-05:00,1.683250,1.687458,1.658002,1.674834,8389600,0.0,0.0
3,2002-02-19 00:00:00-05:00,1.666417,1.666417,1.578047,1.607504,7410400,0.0,0.0
4,2002-02-20 00:00:00-05:00,1.615920,1.662210,1.603296,1.662210,6892800,0.0,0.0

In [ ]:
#4
import requests
from bs4 import BeautifulSoup
#4
import pandas as pd

def extract_gamestop_revenue():
  """Extracts GameStop's quarterly revenue data from Macrotrends."""

  url = 'https://www.macrotrends.net/stocks/charts/GME/gamestop/revenue'
  headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36'}

  response = requests.get(url, headers=headers)
  soup = BeautifulSoup(response.content, 'html.parser')

  table = soup.find('table', {'class': 'table'})
  table_body = table.find('tbody')

  data = []
  for row in table_body.find_all('tr'):
    cols = row.find_all('td')
    if len(cols) >= 2:
      date = cols[0].text.strip()
      revenue = cols[1].text.strip().replace('$', '').replace(',', '')
      data.append([date, revenue])

  df = pd.DataFrame(data, columns=['Date', 'Revenue'])
  df['Revenue'] = pd.to_numeric(df['Revenue'])
  return df

if __name__ == '__main__':
  gamestop_revenue = extract_gamestop_revenue()
  print(gamestop_revenue)

In [ ]:
#5
import yfinance as yf
import pandas as pd
from alpha_vantage.fundamentaldata import FundamentalData
import plotly.express as px

# Extracting Tesla Stock Data
tesla = yf.Ticker("TSLA")
tesla_data = tesla.history(period="max")
tesla_data.reset_index(inplace=True)

# Extracting Tesla Revenue Data
api_key = 'YOUR_API_KEY'  # Replace with your actual Alpha Vantage API key
fd = FundamentalData(key=api_key, output_format='pandas')
revenue_data, meta_data = fd.get_income_statement_annual(symbol='TSLA')

# Merging Data (Assuming 'Date' column is present in revenue data)
merged_data = pd.merge(tesla_data, revenue_data[['fiscalYear', 'totalRevenue']], how='left', on='Date')

# Creating the Dashboard

# Stock Price vs. Date
fig1 = px.line(merged_data, x='Date', y='Close', title='Tesla Stock Price Over Time')

# Revenue vs. Year
fig2 = px.bar(merged_data, x='fiscalYear', y='totalRevenue', title='Tesla Annual Revenue')

# Layout (Optional - Adjust as needed)
fig1.update_layout(margin={'t': 40, 'b': 40, 'l': 20, 'r': 20}, width=700, height=500)
fig2.update_layout(margin={'t': 40, 'b': 40, 'l': 20, 'r': 20}, width=700, height=500)

# Display the Dashboard (using grid layout)
from plotly.subplots import make_subplots

rows = 1
cols = 2
fig = make_subplots(rows=rows, cols=cols, specs=[[{}, {}]])
fig.add_trace(fig1, row=1, col=1)
fig.add_trace(fig2, row=1, col=2)
fig.update_layout(title='Tesla Stock & Revenue Dashboard')
fig.show()

In [ ]:
#6
import yfinance as yf
import pandas as pd
import requests
from bs4 import BeautifulSoup
import plotly.express as px

# Extracting GameStop Stock Data
gamestop = yf.Ticker("GME")
gamestop_data = gamestop.history(period="max")
gamestop_data.reset_index(inplace=True)

# Extracting GameStop Revenue Data (using web scraping)
def extract_gamestop_revenue():
  """Extracts GameStop's quarterly revenue data from Macrotrends."""

  url = 'https://www.macrotrends.net/stocks/charts/GME/gamestop/revenue'
  headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36'}

  response = requests.get(url, headers=headers)
  soup = BeautifulSoup(response.content, 'html.parser')

  table = soup.find('table', {'class': 'table'})
  table_body = table.find('tbody')

  data = []
  for row in table_body.find_all('tr'):
    cols = row.find_all('td')
    if len(cols) >= 2:
      date = cols[0].text.strip()
      revenue = cols[1].text.strip().replace('$', '').replace(',', '')
      data.append([date, revenue])

  df = pd.DataFrame(data, columns=['Date', 'Revenue'])
  df['Revenue'] = pd.to_numeric(df['Revenue'])
  return df

gamestop_revenue = extract_gamestop_revenue()

# Merge Data (Assuming date format is consistent)
merged_data = pd.merge(gamestop_data, gamestop_revenue, on='Date', how='left')

# Create the Dashboard

# Stock Price vs. Date
fig1 = px.line(merged_data, x='Date', y='Close', title='GameStop Stock Price Over Time')

# Revenue vs. Date
fig2 = px.bar(merged_data, x='Date', y='Revenue', title='GameStop Quarterly Revenue')

# Layout (Optional - Adjust as needed)
fig1.update_layout(margin={'t': 40, 'b': 40, 'l': 20, 'r': 20}, width=700, height=500)
fig2.update_layout(margin={'t': 40, 'b': 40, 'l': 20, 'r': 20}, width=700, height=500)

# Display the Dashboard (using grid layout)
from plotly.subplots import make_subplots

rows = 1
cols = 2
fig = make_subplots(rows=rows, cols=cols, specs=[[{}, {}]])
fig.add_trace(fig1, row=1, col=1)
fig.add_trace(fig2, row=1, col=2)
fig.update_layout(title='GameStop Stock & Revenue Dashboard')
fig.show()